import type { ToolSandboxEntry } from "@/sandbox/registry";

export const DEFAULT_TOOL_REGISTRY: readonly ToolSandboxEntry[] = [
  // ── Tier 1: env var isolation ──────────────────────────────────────
  {
    id: "aws",
    name: "AWS CLI",
    binaries: ["aws"],
    tier: "env_var",
    envOverrides: {
      AWS_CONFIG_FILE: "{sandboxDir}/aws/config",
      AWS_SHARED_CREDENTIALS_FILE: "{sandboxDir}/aws/credentials",
    },
    enabledByDefault: true,
  },
  {
    id: "gcloud",
    name: "Google Cloud SDK",
    binaries: ["gcloud", "gsutil", "bq"],
    tier: "env_var",
    envOverrides: { CLOUDSDK_CONFIG: "{sandboxDir}/gcloud" },
    enabledByDefault: true,
  },
  {
    id: "azure",
    name: "Azure CLI",
    binaries: ["az"],
    tier: "env_var",
    envOverrides: { AZURE_CONFIG_DIR: "{sandboxDir}/azure" },
    enabledByDefault: true,
  },
  {
    id: "docker",
    name: "Docker",
    binaries: ["docker"],
    tier: "env_var",
    envOverrides: { DOCKER_CONFIG: "{sandboxDir}/docker" },
    enabledByDefault: true,
  },
  {
    id: "kubectl",
    name: "kubectl",
    binaries: ["kubectl"],
    tier: "env_var",
    envOverrides: { KUBECONFIG: "{sandboxDir}/kube/config" },
    enabledByDefault: true,
  },
  {
    id: "gh",
    name: "GitHub CLI",
    binaries: ["gh"],
    tier: "env_var",
    envOverrides: { GH_CONFIG_DIR: "{sandboxDir}/gh" },
    enabledByDefault: true,
  },
  {
    id: "helm",
    name: "Helm",
    binaries: ["helm"],
    tier: "env_var",
    envOverrides: {
      HELM_CONFIG_HOME: "{sandboxDir}/helm/config",
      HELM_DATA_HOME: "{sandboxDir}/helm/data",
      HELM_CACHE_HOME: "{sandboxDir}/helm/cache",
    },
    enabledByDefault: true,
  },
  {
    id: "terraform",
    name: "Terraform",
    binaries: ["terraform"],
    tier: "env_var",
    envOverrides: { TF_CLI_CONFIG_FILE: "{sandboxDir}/terraform/terraformrc" },
    enabledByDefault: true,
  },
  {
    id: "npm",
    name: "npm",
    binaries: ["npm"],
    tier: "env_var",
    envOverrides: { NPM_CONFIG_USERCONFIG: "{sandboxDir}/npm/npmrc" },
    enabledByDefault: true,
  },
  {
    id: "pip",
    name: "pip",
    binaries: ["pip", "pip3"],
    tier: "env_var",
    envOverrides: { PIP_CONFIG_FILE: "{sandboxDir}/pip/pip.conf" },
    enabledByDefault: true,
  },
  {
    id: "gradle",
    name: "Gradle",
    binaries: ["gradle"],
    tier: "env_var",
    envOverrides: { GRADLE_USER_HOME: "{sandboxDir}/gradle" },
    enabledByDefault: true,
  },
  {
    id: "cargo",
    name: "Cargo",
    binaries: ["cargo"],
    tier: "env_var",
    envOverrides: { CARGO_HOME: "{sandboxDir}/cargo" },
    enabledByDefault: true,
  },
  {
    id: "gpg",
    name: "GPG",
    binaries: ["gpg", "gpg2"],
    tier: "env_var",
    envOverrides: { GNUPGHOME: "{sandboxDir}/gpg" },
    enabledByDefault: true,
  },
  {
    id: "pnpm",
    name: "pnpm",
    binaries: ["pnpm"],
    tier: "env_var",
    envOverrides: { PNPM_HOME: "{sandboxDir}/pnpm" },
    enabledByDefault: true,
  },
  {
    id: "claude",
    name: "Claude Code",
    binaries: ["claude"],
    tier: "env_var",
    envOverrides: {
      CLAUDE_CONFIG_DIR: "{sandboxDir}/claude",
      HAPPIER_CLAUDE_CONFIG_DIR: "{sandboxDir}/claude",
    },
    enabledByDefault: true,
  },
  {
    id: "pulumi",
    name: "Pulumi",
    binaries: ["pulumi"],
    tier: "env_var",
    envOverrides: { PULUMI_HOME: "{sandboxDir}/pulumi" },
    enabledByDefault: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    binaries: ["vercel"],
    tier: "env_var",
    envOverrides: { VERCEL_CONFIG: "{sandboxDir}/vercel" },
    enabledByDefault: true,
  },
  {
    id: "flyio",
    name: "Fly.io",
    binaries: ["flyctl", "fly"],
    tier: "env_var",
    envOverrides: { FLY_CONFIG_DIR: "{sandboxDir}/flyio" },
    enabledByDefault: true,
  },
  {
    id: "supabase",
    name: "Supabase",
    binaries: ["supabase"],
    tier: "env_var",
    envOverrides: { SUPABASE_CONFIG_DIR: "{sandboxDir}/supabase" },
    enabledByDefault: true,
  },
  {
    id: "railway",
    name: "Railway",
    binaries: ["railway"],
    tier: "env_var",
    envOverrides: { RAILWAY_CONFIG_DIR: "{sandboxDir}/railway" },
    enabledByDefault: true,
  },
  {
    id: "netlify",
    name: "Netlify",
    binaries: ["netlify"],
    tier: "env_var",
    envOverrides: { NETLIFY_CONFIG_DIR: "{sandboxDir}/netlify" },
    enabledByDefault: true,
  },

  // ── Tier 2: HOME wrapper isolation ─────────────────────────────────
  {
    id: "aliyun",
    name: "Aliyun CLI",
    binaries: ["aliyun"],
    tier: "home_wrapper",
    homeConfigPaths: [".aliyun"],
    enabledByDefault: true,
  },
  {
    id: "lark-cli",
    name: "Lark CLI (Feishu)",
    binaries: ["lark-cli"],
    tier: "home_wrapper",
    homeConfigPaths: [".lark-cli"],
    enabledByDefault: true,
  },
  {
    id: "ossutil",
    name: "ossutil",
    binaries: ["ossutil", "ossutil64"],
    tier: "home_wrapper",
    homeConfigPaths: [".ossutilconfig"],
    enabledByDefault: true,
  },
  {
    id: "ansible",
    name: "Ansible",
    binaries: ["ansible", "ansible-playbook"],
    tier: "home_wrapper",
    homeConfigPaths: [".ansible"],
    enabledByDefault: true,
  },
  {
    id: "vagrant",
    name: "Vagrant",
    binaries: ["vagrant"],
    tier: "home_wrapper",
    homeConfigPaths: [".vagrant.d"],
    enabledByDefault: true,
  },
];
